# Change these first
owner: MridulS # Your GitHub username
repo: test_status_page # Your Github repository name

# Add your sites here
sites:
  - name: GESIS Notebooks - Persistent BinderHub
    url: https://notebooks.gesis.org
  - name: GESIS Notebooks - BinderHub
    url: https://notebooks.gesis.org/binder
  - name: GESIS Notebooks - Gallery
    url: https://notebooks.gesis.org/gallery/
 # Hackish way to check the JSON fields
  - name: Persistent BinderHub - Health
    url: https://notebooks.gesis.org/services/binder/health
    __dangerous__body_degraded: '{"ok": true,'
  - name: Persistent BinderHub - Docker
    url: https://notebooks.gesis.org/services/binder/health
    __dangerous__body_degraded: '{"service": "Docker registry", "ok": true}'
  - name: BinderHub - Health
    url: https://notebooks.gesis.org/binder/health
    __dangerous__body_degraded: '{"ok": false,'
  - name: BinderHub - Docker
    url: https://notebooks.gesis.org/binder/health
    __dangerous__body_degraded: '{"service": "Docker registry", "ok": false}'

status-website:
  baseUrl: /test_status_page
  logoUrl: https://raw.githubusercontent.com/gesiscss/orc/master/load_balancer/static/images/logo/logo_new.svg
  name: "GESIS Notebooks"
#   introTitle: "GESIS notebooks"
  introMessage: "Status page for various services running on GESIS notebooks."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/gesiscss/orc

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
