# Change these first
owner: gesisnotebooks # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: GESIS Notebooks - Persistent BinderHub
    url: https://notebooks.gesis.org

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/gesiscss/orc/master/load_balancer/static/images/logo/logo_new.svg
  name: "GESIS Notebooks"
#   introTitle: "GESIS notebooks"
  introMessage: "Status page tracking various services running at GESIS notebooks. This status page tracks the deployed Persistent BinderHub, BinderHub (available through mybinder.org), and Gallery."
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/gesiscss/orc
    - title: GESIS Notebooks
      href: https://notebooks.gesis.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
