# Change these first
owner: MridulS # Your GitHub username
repo: test_status_page # Your Github repository name

# Add your sites here
sites:
  - name: GESIS Notebooks - Persistent BinderHub
    url: https://notebooks.gesis.org
  - name: GESIS Notebooks - BinderHub
    url: https://notebooks.gesis.org/binder
  - name: GESIS Notebooks - Gallery
    url: https://notebooks.gesis.org/gallery/
  - name: JupyterHub API
    url: https://notebooks.gesis.org/hub/api/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /test_status_page
  logoUrl: https://github.com/gesiscss/orc/blob/master/load_balancer/static/images/logo/logo_big.png
  name: GESIS-notebooks
  introTitle: "GESIS notebooks"
  introMessage: Status page for various services running on GESIS notebooks.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
